name: 'banking_dw'
version: '1.0.0'
config-version: 2

profile: 'banking_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  banking_dw:
    +materialized: view
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table