version: 2

models:

  - name: dim_customer
    description: "Dimension table containing customer master data."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: fact_transaction
    description: "Fact table storing all financial transactions."
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null

      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_account')
              field: account_id

      - name: transaction_date
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

  - name: int_daily_balance
    description: "Daily running balance per account."
    columns:
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_account')
              field: account_id

      - name: date
        tests:
          - not_null

      - name: running_balance
        description: "Cumulative balance."
